version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: alugue_sol_db
    volumes:
      - ./wp-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass

  wordpress:
    image: wordpress:6.5
    container_name: alugue_sol_wp
    depends_on:
      - db
    ports:
      - "8000:80"
    volumes:
      - ./wp-html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
